### PR TITLE
WIP: Revert "p2p/discover, p2p/enode: rework endpoint proof handling, pack…

### LINKED ISSUE #28: can't sync chain with latest master (classic)
I don't have better or more specific errors or logs yet, but can't seem to sync with geth with `--classic` at latest master (`569a2b039b560836de397c2e059497719aea49a6`) version. Have not investigated other chains yet.

Have tried/am trying full and fast sync modes.

```
TRACE[02-07|12:26:07.101] Found seed node in database              id=ff070c68559f5406 addr=104.155.176.151:30303 age=430434h26m7.101475902s                                                                                                                                                                                                                         [0/1791]
TRACE[02-07|12:26:07.101] Found seed node in database              id=a325d4e8dc3bfb45 addr=104.154.136.117:30303 age=430434h26m7.101491276s
TRACE[02-07|12:26:07.101] Found seed node in database              id=b822f0f3d3d19c91 addr=104.198.71.200:30303  age=430434h26m7.10150411s
TRACE[02-07|12:26:07.101] Found seed node in database              id=8d853f06e0e14f37 addr=144.76.238.49:30303   age=430434h26m7.101517912s
TRACE[02-07|12:26:07.101] Found seed node in database              id=4404737930844c9f addr=144.76.238.49:30306   age=430434h26m7.101530782s
TRACE[02-07|12:26:07.101] Dial task done                           task="discovery lookup"
TRACE[02-07|12:26:07.101] Skipping dial candidate                  id=b822f0f3d3d19c91 addr=104.198.71.200:30303  err="recently dialed"
TRACE[02-07|12:26:07.101] Skipping dial candidate                  id=4404737930844c9f addr=144.76.238.49:30306   err="already dialing"
TRACE[02-07|12:26:07.101] Skipping dial candidate                  id=3064061e8cb4d357 addr=162.243.55.45:30303   err="recently dialed"
TRACE[02-07|12:26:07.101] New dial task                            task="discovery lookup"
TRACE[02-07|12:26:10.101] Dial error                               task="dyndial 7443237b72d4b4c6 174.112.32.157:30303"  err="dial tcp 174.112.32.157:30303: i/o timeout"
TRACE[02-07|12:26:10.101] Dial task done                           task="dyndial 7443237b72d4b4c6 174.112.32.157:30303"
TRACE[02-07|12:26:10.101] Skipping dial candidate                  id=8d853f06e0e14f37 addr=144.76.238.49:30303   err="already dialing"
TRACE[02-07|12:26:10.101] Skipping dial candidate                  id=3064061e8cb4d357 addr=162.243.55.45:30303   err="recently dialed"
TRACE[02-07|12:26:10.101] Skipping dial candidate                  id=4404737930844c9f addr=144.76.238.49:30306   err="already dialing"
TRACE[02-07|12:26:10.101] Skipping dial candidate                  id=8d853f06e0e14f37 addr=144.76.238.49:30303   err="already dialing"
TRACE[02-07|12:26:11.101] Found seed node in database              id=7443237b72d4b4c6 addr=174.112.32.157:30303  age=430434h26m11.101535327s
TRACE[02-07|12:26:11.101] Found seed node in database              id=08cf9ce89840d753 addr=52.206.67.235:30303   age=430434h26m11.101568983s
TRACE[02-07|12:26:11.101] Found seed node in database              id=3064061e8cb4d357 addr=162.243.55.45:30303   age=430434h26m11.101594117s
TRACE[02-07|12:26:11.101] Found seed node in database              id=ff070c68559f5406 addr=104.155.176.151:30303 age=430434h26m11.101611727s
TRACE[02-07|12:26:11.101] Found seed node in database              id=a325d4e8dc3bfb45 addr=104.154.136.117:30303 age=430434h26m11.101626607s
TRACE[02-07|12:26:11.101] Found seed node in database              id=b822f0f3d3d19c91 addr=104.198.71.200:30303  age=430434h26m11.101640812s
TRACE[02-07|12:26:11.101] Found seed node in database              id=8d853f06e0e14f37 addr=144.76.238.49:30303   age=430434h26m11.101656435s
TRACE[02-07|12:26:11.101] Found seed node in database              id=4404737930844c9f addr=144.76.238.49:30306   age=430434h26m11.101671715s
TRACE[02-07|12:26:11.101] Dial task done                           task="discovery lookup"
TRACE[02-07|12:26:11.101] Skipping dial candidate                  id=4404737930844c9f addr=144.76.238.49:30306   err="already dialing"
TRACE[02-07|12:26:11.101] Skipping dial candidate                  id=08cf9ce89840d753 addr=52.206.67.235:30303   err="recently dialed"
TRACE[02-07|12:26:11.101] Skipping dial candidate                  id=3064061e8cb4d357 addr=162.243.55.45:30303   err="recently dialed"
TRACE[02-07|12:26:11.101] Skipping dial candidate                  id=4404737930844c9f addr=144.76.238.49:30306   err="already dialing"
TRACE[02-07|12:26:11.101] New dial task                            task="discovery lookup"
TRACE[02-07|12:26:11.198] >> PING/v4                               id=08cf9ce89840d753 addr=52.206.67.235:30303   err=nil
DEBUG[02-07|12:26:11.698] Removed dead node                        b=13 id=08cf9ce89840d753 ip=52.206.67.235   checks=0
DEBUG[02-07|12:26:14.949] Recalculated downloader QoS values       rtt=20s confidence=1.000 ttl=1m0s
TRACE[02-07|12:26:15.101] Found seed node in database              id=7443237b72d4b4c6 addr=174.112.32.157:30303  age=430434h26m15.101965453s
TRACE[02-07|12:26:15.102] Found seed node in database              id=08cf9ce89840d753 addr=52.206.67.235:30303   age=430434h26m15.102026912s
TRACE[02-07|12:26:15.102] Found seed node in database              id=3064061e8cb4d357 addr=162.243.55.45:30303   age=430434h26m15.102059376s
TRACE[02-07|12:26:15.102] Found seed node in database              id=ff070c68559f5406 addr=104.155.176.151:30303 age=430434h26m15.10208267s
TRACE[02-07|12:26:15.102] Found seed node in database              id=a325d4e8dc3bfb45 addr=104.154.136.117:30303 age=430434h26m15.1021051s
TRACE[02-07|12:26:15.102] Found seed node in database              id=b822f0f3d3d19c91 addr=104.198.71.200:30303  age=430434h26m15.102126317s
TRACE[02-07|12:26:15.102] Found seed node in database              id=8d853f06e0e14f37 addr=144.76.238.49:30303   age=430434h26m15.102157043s
TRACE[02-07|12:26:15.102] Found seed node in database              id=4404737930844c9f addr=144.76.238.49:30306   age=430434h26m15.102178112s
TRACE[02-07|12:26:15.102] Dial task done                           task="discovery lookup"
TRACE[02-07|12:26:15.102] Skipping dial candidate                  id=7443237b72d4b4c6 addr=174.112.32.157:30303  err="recently dialed"
TRACE[02-07|12:26:15.102] Skipping dial candidate                  id=4404737930844c9f addr=144.76.238.49:30306   err="already dialing"
TRACE[02-07|12:26:15.102] Skipping dial candidate                  id=08cf9ce89840d753 addr=52.206.67.235:30303   err="recently dialed"
TRACE[02-07|12:26:15.102] New dial task                            task="dyndial 3064061e8cb4d357 162.243.55.45:30303"
TRACE[02-07|12:26:15.102] New dial task                            task="discovery lookup"
TRACE[02-07|12:26:15.544] Skipping dial candidate                  id=08cf9ce89840d753 addr=52.206.67.235:30303   err="recently dialed"
TRACE[02-07|12:26:15.544] Skipping dial candidate                  id=8d853f06e0e14f37 addr=144.76.238.49:30303   err="already dialing"
TRACE[02-07|12:26:15.544] Skipping dial candidate                  id=4404737930844c9f addr=144.76.238.49:30306   err="already dialing"
TRACE[02-07|12:26:15.687] >> PING/v4                               id=7443237b72d4b4c6 addr=174.112.32.157:30303  err=nil
DEBUG[02-07|12:26:16.188] Removed dead node                        b=15 id=7443237b72d4b4c6 ip=174.112.32.157  checks=0
DEBUG[02-07|12:26:16.414] Adding p2p peer                          name=Parity/v1.10.6-stabl...                                               addr=162.243.55.45:30303   peers=1
TRACE[02-07|12:26:16.414] Skipping dial candidate                  id=08cf9ce89840d753 addr=52.206.67.235:30303   err="recently dialed"
TRACE[02-07|12:26:16.414] Skipping dial candidate                  id=4404737930844c9f addr=144.76.238.49:30306   err="already dialing"
TRACE[02-07|12:26:16.414] Starting protocol eth/63                 id=3064061e8cb4d357 conn=dyndial
TRACE[02-07|12:26:16.414] connection set up                        id=3064061e8cb4d357 addr=162.243.55.45:30303   conn=dyndial inbound=false
TRACE[02-07|12:26:16.414] Dial task done                           task="dyndial 3064061e8cb4d357 162.243.55.45:30303"
DEBUG[02-07|12:26:16.414] Ethereum peer connected                  id=3064061e8cb4d357 conn=dyndial name=Parity/v1.10.6-stable-bc0d134bb-20180605/x86_64-linux-gnu/rustc1.26.1
TRACE[02-07|12:26:16.414] Skipping dial candidate                  id=08cf9ce89840d753 addr=52.206.67.235:30303   err="recently dialed"
TRACE[02-07|12:26:16.414] Skipping dial candidate                  id=4404737930844c9f addr=144.76.238.49:30306   err="already dialing"
TRACE[02-07|12:26:18.104] Dial error                               task="dyndial 8d853f06e0e14f37 144.76.238.49:30303"   err="dial tcp 144.76.238.49:30303: i/o timeout"
TRACE[02-07|12:26:18.104] Dial error                               task="dyndial 4404737930844c9f 144.76.238.49:30306"   err="dial tcp 144.76.238.49:30306: i/o timeout"
TRACE[02-07|12:26:18.104] Dial task done                           task="dyndial 8d853f06e0e14f37 144.76.238.49:30303"
TRACE[02-07|12:26:18.104] Skipping dial candidate                  id=8d853f06e0e14f37 addr=144.76.238.49:30303   err="recently dialed"
TRACE[02-07|12:26:18.104] Skipping dial candidate                  id=08cf9ce89840d753 addr=52.206.67.235:30303   err="recently dialed"
TRACE[02-07|12:26:18.104] Skipping dial candidate                  id=4404737930844c9f addr=144.76.238.49:30306   err="already dialing"
TRACE[02-07|12:26:18.104] Dial task done                           task="dyndial 4404737930844c9f 144.76.238.49:30306"
TRACE[02-07|12:26:18.104] Skipping dial candidate                  id=08cf9ce89840d753 addr=52.206.67.235:30303   err="recently dialed"
TRACE[02-07|12:26:18.104] Skipping dial candidate                  id=8d853f06e0e14f37 addr=144.76.238.49:30303   err="recently dialed"
TRACE[02-07|12:26:18.104] Skipping dial candidate                  id=3064061e8cb4d357 addr=162.243.55.45:30303   err="already connected"
TRACE[02-07|12:26:19.101] Found seed node in database              id=7443237b72d4b4c6 addr=174.112.32.157:30303  age=430434h26m19.101778486s
TRACE[02-07|12:26:19.101] Found seed node in database              id=08cf9ce89840d753 addr=52.206.67.235:30303   age=430434h26m19.101818345s
TRACE[02-07|12:26:19.101] Found seed node in database              id=3064061e8cb4d357 addr=162.243.55.45:30303   age=430434h26m19.101841095s
TRACE[02-07|12:26:19.101] Found seed node in database              id=ff070c68559f5406 addr=104.155.176.151:30303 age=430434h26m19.101860691s
TRACE[02-07|12:26:19.101] Found seed node in database              id=a325d4e8dc3bfb45 addr=104.154.136.117:30303 age=430434h26m19.10187623s
TRACE[02-07|12:26:19.101] Found seed node in database              id=b822f0f3d3d19c91 addr=104.198.71.200:30303  age=430434h26m19.101891113s
TRACE[02-07|12:26:19.101] Found seed node in database              id=8d853f06e0e14f37 addr=144.76.238.49:30303   age=430434h26m19.101905873s
TRACE[02-07|12:26:19.101] Found seed node in database              id=4404737930844c9f addr=144.76.238.49:30306   age=430434h26m19.101920199s
TRACE[02-07|12:26:19.101] Dial task done                           task="discovery lookup"
TRACE[02-07|12:26:19.101] Skipping dial candidate                  id=8d853f06e0e14f37 addr=144.76.238.49:30303   err="recently dialed"
TRACE[02-07|12:26:19.101] Skipping dial candidate                  id=4404737930844c9f addr=144.76.238.49:30306   err="recently dialed"
TRACE[02-07|12:26:19.101] Skipping dial candidate                  id=08cf9ce89840d753 addr=52.206.67.235:30303   err="recently dialed"
TRACE[02-07|12:26:19.102] New dial task                            task="discovery lookup"
TRACE[02-07|12:26:19.154] Registering sync peer                    peer=3064061e8cb4d357
DEBUG[02-07|12:26:19.154] Fetching batch of headers                id=3064061e8cb4d357 conn=dyndial count=1  fromnum=1920000 skip=0  reverse=false
DEBUG[02-07|12:26:19.757] Peer discarded announcement              peer=3064061e8cb4d357 number=7448160 hash=bbeb1e…2c7b2c distance=7448160
DEBUG[02-07|12:26:19.872] Verified to be on the same side of the DAO fork id=3064061e8cb4d357 conn=dyndial
```

For comparison, side by side testing at 
```
$ git rev-parse HEAD
da85a4469860e1b0dd6109b1d029ad285647e914
```

seems to be working fine.

Will follow up with more investigation and information. May be worth cross referencing with upstream on this, and auditing the latest merge from there.

### PR DESCRIPTION
**Pull request by whilei**
…et logging (#18963)"

This reverts commit f0c6f921408d97251b1b554a7ea83d020c70a2da.

--- 

It appears this patch introduced a bug that prevents a node running `--classic` to begin synchronizing. 

This revert fixes #28. 

TODO: why?

### CODE REVIEW

**Comment by whilei** [comment]
This actually might not completely solve #28. Not sure. I'm seeing some sync progress (where there was none before) but the clients are seeming to flatline... maybe when they hit an error with a peer. 

The last definitely fully-working-for-me commit is 29e583bc4bd90fafb2ad3cdacfccbf6d64b08055.

**Comment by whilei** [comment]
Seems to be working a lot better when I don't run a whole bunch of geth instances on my computer at the same time.

**Comment by whilei** [comment]
I've edited the title to reflect that I'm working on this, albeit indirectly at the moment; I'm working to get Hive testing set up so we can actually show that this is failing and if and when it is actually fixed.

**Comment by soc1c** [comment]
I would advise against reverting that and rather finding out what's causing the issues with classic and attempt to fix it.

**Comment by whilei** [comment]
Yea, me too. And this PR is now out of date and pretty useless (will close). I'm working on getting Hive up and running so that we can systematically diagnose this issue (and potential further issues like it) and then attempt to fix it.

But of course there is a matter of urgency on [this issue](https://github.com/ethoxy/multi-geth/issues/28) too, so, as ugly as it is, it might be worth keeping an open mind to unfortunate "it just works" solutions as long as they can be adequately vetted to not be dangerous or perplexingly arbitrary.

**Pull request closed without merging**
