### PR TITLE
Enable Kotti Atlantis hard fork

### PR DESCRIPTION
**Pull request by sorpaas**
Kotti EIP-158 and Byzantium happening on `716_617`. Note that it looks like we don't yet support Morden testnet.

### CODE REVIEW

**Comment by soc1c** [comment]
ref https://github.com/eth-classic/kensington/issues/7#issuecomment-500409858 and https://github.com/ethereum/go-ethereum/commit/aad4890082c1624795991d534db9497c8b63630d

**Comment by soc1c** [comment]
How are you handling EIPs ~~160,~~ 161 and 170?

**Comment by sorpaas** [comment]
@soc1c They're named `EIP158`.

**Review by meowsbits — APPROVED** [review]
This looks sufficient to me. 

Alternatively, one could enable each of the corresponding feature blocks to do the same thing, but that would just a different way of doing it. Although I might propose later to move to that just because it's more descriptive, I'm fine now doing this since we can simply swap 1:1 whenever.

**Pull request merged**
