### PR TITLE
forkid: add classic forkid test cases

### PR DESCRIPTION
**Pull request by meowsbits**
Adds `forkid` test cases for Classic networks. 

`Classic` and `Kotti` cases don't pass. 

Using an invalid forkid value for geth's default eth/64+ protocol can result in less successful peer discovery.

--- 

- ECIP1082 PR Classic implementation patterns for `forkid`, with change proposed to move to `Final` status: https://github.com/ethereumclassic/ECIPs/pull/311
  + Latest Clasic `forkid` spec file: https://github.com/ethereumclassic/ECIPs/blob/b1c48b16d58de8ac6b8a159eef66901d9d80c8af/_specs/ecip-1082.md

### CODE REVIEW

**Review by sorpaas — CHANGES_REQUESTED** [review]
The test case difference is due to 1920000. I don't think omitting fork block 1920000 is a good idea. Can you explain why that won't cause issues when it syncs between 1920000 to 2500000?

**Comment by meowsbits** [comment]
Thanks for the review! Since this is a question/concern about the ECIP (as opposed to the test case implementation), I've followed up at the ECIP-1082 Discussions forum, here: https://github.com/ethereumclassic/ECIPs/issues/294#issuecomment-603478368

**Comment by sorpaas** [comment]
> ETC clients, however, will have a harder time differentiating their chain, since state may not yet be downloaded. In the worst case scenario, an ETC geth might fast sync from an ETH node as high as the next fork as you've mentioned, and discover then that they'd been mislead, and need to find another peer with which to negotiate a common ancestor, effectively using trial and error to find a peer that serves the valid chain.

As you mentioned, omitting 1920000 in the fork block will indeed cause issues, thus I don't believe it's a good idea. With the current configuration, ETC clients will not suffer from any "harder time differentiating the chain". This is exactly what forkid is designed to do.

> This scenario can easily be avoided by adding the relevant hash for 1920000 to a white or black list that would be validated against during the Header Validation, perhaps somewhere like here.

No I don't think that works. The code you mentioned only touches header validation, but the hashes are not checked during networking. So the above "harder time differentiating the chain" still happens even with this change.

As this is basically a feature request to remove 1920000 from forkid list, I've created a new issue. https://github.com/multi-geth/multi-geth/issues/142
However, so far I'm not seeing compelling reasons to do it yet.

**Comment by sorpaas** [comment]
@meowsbits Hmm, no. After reading EIP-2124 I believe 1920000 **has to** be eliminated from forkid list. It will otherwise have the issue that it will have "harder time differentiating the chain", but not as you said -- with it.

Let me submit the code needed for getting the test cases to pass. Can't really merge this PR though as it only contains the test cases. Closing.

**Comment by meowsbits** [comment]
> It will otherwise have the issue that it will have "harder time differentiating the chain", but not as you said -- with it.

I think I see what you mean, and maybe see the misunderstanding. The two contexts here are networking and block processing.  I meant "harder time differentiating the chain" in the context of block processing during fast sync (since effort may be wasted downloading irrelevant headers).  My second point speaks directly to the networking point you're making, I think:

> clients implementing this protocol are able to disambiguate networks sooner, avoiding the above issue altogether.

**Pull request closed without merging**
