### PR TITLE
*: apply patch diffing essential multi-geth vs current master

### PR DESCRIPTION
**Pull request by meowsbits**
This patch is intended to bring multi-geth as close as possible (again) to _essential_ multi-geth; and with that as close as possible to upstream go-ethereum. The size and scope tell us that multi-geth master was pretty out-of-whack. 

This patch would bring multi-geth master up-to-date with go-ethereum master 6269e5574c024bb82617b33f673550231b3a3b37, which is at or above 1.8.27.

Reviewing this PR has two important diffs to review:
1. Diffing 'essential multi-geth' (this tip) vs. current multi-geth. [This](https://gist.github.com/22aebfb401036774d2661b8bc9cc086e) is the changeset that will bring multi-geth back to a clean and healthy state.
2. Diffing essential multi-geth vs. go-ethereum. [This](https://gist.github.com/whilei/6f4852d71f3f52855168703c02fef803) is what makes multi-geth multi-geth.

A wise reviewer with a human-sized amount of time for this sort of thing will prefer to review the patch against go-ethereum (2).

I'll include links to gists for those patches for quick convenience; but you shouldn't take my word for them being accurate, and instead should generate them yourself:

```
git remote add origin https://github.com/ethereum/go-ethereum
git remote add mg https://github.com/multi-geth/multi-geth
git fetch --all
git checkout -B origin-master origin/master
git checkout -B mg-master mg/master
git checkout -B mg-master-pr mg/patch/fix-mg-master-downstream # this pr's head branch
git diff --binary origin-master mg-master-pr > multi-geth-pr-vs-go-ethereum.patch
git diff --binary mg-master mg-master-pr > multi-geth-pr-vs-multi-geth.patch
```

---

- Why one commit?
> Finding and fixing the diff between multi-geth as-is and should-be w/r/t upstream required me in my limited intelligence and time to do some `git reset`s and `rebase`s. This broke some history, and in order to be able to propose a "Mergeable" :heavy_check_mark:  changeset I had to propose the patch instead of being able to propose a forked history. Further, experience shows that Github PRs with more than 250 commits and 1k files & +/-100k lines are liable to break your browser.

- How did it get like this?
> It would be good to understand more precisely than I do at this moment, but I'm pretty sure it has to do with: 
>  - `git merge` is not that great; it can be unpredictable and sometimes just gets things wrong
>  - deleted/removed/untracked files were not removed (maybe not `clean`ed?) from multi-geth (eg whisper/whisperv5/)

- ... And how can we keep this from happening again?
>  - A first step will be to include and review both patch "views" when proposing changes to multi-geth; it's important to keep diffs from perspective of both upstream and downstream codebases in mind. In order to do this, perhaps we should build a PR pattern around _two_ PRs per proposal -- one to the canonical `master` and a second to a dedicated upstream-tracking `origin-master` to prove level-ness (showing consistency and focused diffing between iterations of the what-makes-multi-geth-multi-geth patches). 
>    + To this point, I'll do the proposed "second PR" against an upstream tracker branch and we can see how that works. ~~Will edit with link.~~ #71 
>    + This is mostly important for "upstreaming" patches; iterative multi-geth-only feature or fix patches are usually smaller and more reviewable.
>  - A second step might include using a redundant VC system to confirm patch content, eg. `pijul`? I'm not sure exactly what this would look like, but might be worth exploring a little more given pijul's claims for robust patching.

---

### Further inquiry

- [ ] This patch doesn't edit CI configs at all, although there have been edits to them on go-ethereum. Are we as level as possible and still configured properly for ourselves?

### CODE REVIEW

**Comment by sorpaas** [comment]
LGTM. I think we can merge this once we finished v1.8.27 release!

> ... And how can we keep this from happening again?

Another idea would be to duplicate all merged `go-ethereum` PRs in this repo as well. In this way we can have our own release schedule without worrying about upstream's branching rules.

**Comment by sorpaas** [comment]
> it's important to keep diffs from perspective of both upstream and downstream codebases in mind

TBH I think this was not the issue that caused our merge hell. The issue, if I perceive it correctly, was that we merged several tags (`v1.8.x`) which was on the `release/1.8` branch, but also merged `master` several times in the middle. That was where the merge history got broken.

**Review by sorpaas — APPROVED** [review]

**Comment by meowsbits** [comment]
> That was where the merge history got broken.

Ah, I see... so we were accidentally "un-backporting" some changes? 

Granted there were merge hells ;) -- do you think these hells (messy auto-merges, too-large and confusingly overlapping merges, repetitive and hard to manage conflicts) are where the codebase discrepancy arose from?

In your opinion which branch pattern is best to merge with ours from - `release/xxx` or `master`? Or right from tags? 

Just for information, attaching a screenshot of latest go-ethereum master, release/*, and tag 1.8.x commit graph. It illustrates some of the inconsistencies upstream between master and release branches, as well as how the release branches are used for tags.

Screenshot_20190423_162747

**Comment by meowsbits** [comment]
> Another idea would be to duplicate all merged go-ethereum PRs in this repo as well.

In order to do this, we'd want to maintain congruent branching (and tagging) schemes as well I assume.

**Comment by meowsbits** [comment]
> LGTM. I think we can merge this once we finished v1.8.27 release!

OK, but I think we should do this ASAP. As I understand, [this fix](https://github.com/multi-geth/multi-geth/commit/9476ffaa669cff146fb25bb9ed6e472e7a794d2e) is not really a fix and [the still failing test](https://travis-ci.org/multi-geth/multi-geth/jobs/518554943#L612) is an indication of an iceberg of problems (supported by fact that code varies from go-ethereum master so significantly).

... and propose that we make an additional tag and release on top of this merge, like `1.8.27-masochist` or whatever.

**Comment by meowsbits** [comment]
I've still got my eye on eventually figuring out a way to keep the "essential multi-geth changeset" somehow visible, `apply`-able, and reviewable. Seems important to me to be able to understand (and communicate) well the diff of our codebase vs. upstream; for sake of review, maintenance, and developer accessibility.  We want to know if merge hells become divergent merging hells :joy_cat: :fire:

**Comment by meowsbits** [comment]
:rocket: :+1:

**Pull request merged**
